package xw.cn.daoexample.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import xw.cn.daoexample.bean.RepositoryNote;

import xw.cn.daoexample.db.RepositoryNoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig repositoryNoteDaoConfig;

    private final RepositoryNoteDao repositoryNoteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        repositoryNoteDaoConfig = daoConfigMap.get(RepositoryNoteDao.class).clone();
        repositoryNoteDaoConfig.initIdentityScope(type);

        repositoryNoteDao = new RepositoryNoteDao(repositoryNoteDaoConfig, this);

        registerDao(RepositoryNote.class, repositoryNoteDao);
    }
    
    public void clear() {
        repositoryNoteDaoConfig.clearIdentityScope();
    }

    public RepositoryNoteDao getRepositoryNoteDao() {
        return repositoryNoteDao;
    }

}
